<a href="https://colab.research.google.com/github/tanvi1100/travel-hospitality-data-portfolio/blob/main/Travel_Hospitality_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Travel & Hospitality Data Analysis

## Week 1: Hotel Booking Analysis

### Objective
Analyze hotel booking data to understand pricing trends, destination demand, and customer behavior using Python and Pandas.

In [1]:
import pandas as pd

Creating Dataset

In [3]:
data = [
    (1, 101, 'Luxury Stay Hotel', 'New York', 450, 4.8, '2026-01-01'),
    (2, 102, 'Ocean View Resort', 'Miami', 320, 4.5, '2026-01-02'),
    (3, 103, 'City Comfort Inn', 'Chicago', 180, 4.0, '2026-01-03'),
    (4, 104, 'Royal Palace Hotel', 'New York', 600, 4.9, '2026-01-04'),
    (5, 105, 'Beachside Escape', 'Los Angeles', 520, 4.7, '2026-01-05'),
    (6, 106, 'Urban Stay', 'Chicago', 200, 3.9, '2026-01-06'),
    (7, 107, 'Grand Luxe Hotel', 'Miami', 700, 4.9, '2026-01-07'),
    (8, 108, 'Budget Comfort', 'Dallas', 120, 3.8, '2026-01-08'),
    (9, 109, 'Skyline Suites', 'New York', 800, 4.9, '2026-01-09'),
    (10, 110, 'Sunset Resort', 'Los Angeles', 400, 4.6, '2026-01-10')
]

columns = [
    "booking_id",
    "user_id",
    "hotel_name",
    "city",
    "price",
    "rating",
    "booking_date"
]

df = pd.DataFrame(data, columns=columns)

df.head()

,booking_id,user_id,hotel_name,city,price,rating,booking_date
0,1,101,Luxury Stay Hotel,New York,450,4.8,2026-01-01
1,2,102,Ocean View Resort,Miami,320,4.5,2026-01-02
2,3,103,City Comfort Inn,Chicago,180,4.0,2026-01-03
3,4,104,Royal Palace Hotel,New York,600,4.9,2026-01-04
4,5,105,Beachside Escape,Los Angeles,520,4.7,2026-01-05

First Analysis

In [4]:
print("Total Bookings:", len(df))
print("Average Booking Price:", round(df["price"].mean(), 2))

Total Bookings: 10
Average Booking Price: 429.0

Popular Cities

In [5]:
df.groupby("city").size().sort_values(ascending=False)

city
New York       3
Chicago        2
Los Angeles    2
Miami          2
Dallas         1
dtype: int64